with open ('numar.txt','r') as f:
    a=f.readline()
    n=int(a)
with open ('inmultire.txt','w') as f:
    f.write(str(n*1))
    f.write('      ')
    f.write(str(n*2))
    f.write('      ')
    f.write(str(n*3))
    f.write('   ')
    f.write(str(n*4))
    f.write('   ')
    f.write(str(n*5))
    f.write('   ')
    f.write(str(n*6))
    f.write('   ')
    f.write(str(n*7))
    f.write('   ')
    f.write(str(n*8))
    f.write('   ')
    f.write(str(n*9))
    f.write('   ')
    f.write(str(n*10))